llm_params:
  # 认证相关参数
  api_key: "sk-your-key-here"
  base_url: "https://api.deepseek.com/v1" 
  
  # 模型参数
  model: "deepseek-ai/DeepSeek-V3"
  temperature: 0.7 
  max_tokens: 2000        # 最大生成token数
  frequency_penalty: 0.0  # 重复惩罚系数
  presence_penalty: 0.0   # 主题重复惩罚


mgr:
  # messages 相关
  history_length: 10 # 上下文最大长度
  time_window: 3600  # 上下文时间窗口
  time_injection: 2        # system_prompt 时间注入
  weather_injection: 0     # system_天气 时间注入
  db_path: ''

system_prompt:
  template: template.md