params:
  api_key: ...
  base_url: ...
  model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  temperature: 0.5
  max_tokens: 100
  frequency_penalty: 0.0
  presence_penalty: 0.0
messages:
  history:
    db_path: ...
    max_length: 0
    time_window: 86400
  system_prompt:
    template: my_config
    role: atri
  injections:
    time: 2
    weather: 0